// SDK generator template — copy to <skill>/src/<sdk-dir>/generate.ts.
// Reads the API spec from <skill>/resources/swagger.json and regenerates
// types.ts, actions/, and index.ts next to this script.
// Run from <skill>/src with: npx tsx <sdk-dir>/generate.ts
//
// Input contract: Swagger 2.0 JSON. If the API publishes OpenAPI 3 or any
// other format, convert it to Swagger 2.0 first (see references/codegen.md).
// Do not fork this generator per format.
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

type OperationCategory = "read" | "create" | "update" | "delete";

// Ask the user which categories they want before generating. Read-only is the
// safe default; only enable write categories when the user explicitly asks.
const ENABLED_CATEGORIES: Readonly<Record<OperationCategory, boolean>> = {
  read: true,
  create: false,
  update: false,
  delete: false,
};

const HTTP_METHODS = ["get", "post", "put", "patch", "delete"] as const;

type HttpMethod = (typeof HTTP_METHODS)[number];

const METHOD_CATEGORIES: Readonly<Record<HttpMethod, OperationCategory>> = {
  get: "read",
  post: "create",
  put: "update",
  patch: "update",
  delete: "delete",
};

interface SwaggerSchema {
  readonly $ref?: string;
  readonly type?: string;
  readonly enum?: readonly (string | number | boolean)[];
  readonly items?: SwaggerSchema;
  readonly properties?: Readonly<Record<string, SwaggerSchema>>;
  readonly required?: readonly string[];
  readonly additionalProperties?: SwaggerSchema | boolean;
  readonly allOf?: readonly SwaggerSchema[];
}

interface SwaggerParameter {
  readonly name: string;
  readonly in: "path" | "query" | "body" | "formData" | "header";
  readonly required?: boolean;
  readonly type?: string;
  readonly items?: SwaggerSchema;
  readonly enum?: readonly (string | number | boolean)[];
  readonly schema?: SwaggerSchema;
}

interface SwaggerOperation {
  readonly summary?: string;
  readonly deprecated?: boolean;
  readonly parameters?: readonly SwaggerParameter[];
  readonly responses?: Readonly<Record<string, { readonly schema?: SwaggerSchema }>>;
}

type SwaggerPathItem = Partial<Record<HttpMethod, SwaggerOperation>> & {
  readonly parameters?: readonly SwaggerParameter[];
};

interface SwaggerDocument {
  readonly paths: Readonly<Record<string, SwaggerPathItem>>;
  readonly definitions?: Readonly<Record<string, SwaggerSchema>>;
}

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const swaggerPath = path.resolve(scriptDir, "../../resources/swagger.json");
const typesPath = path.join(scriptDir, "types.ts");
const actionsDir = path.join(scriptDir, "actions");
const indexPath = path.join(scriptDir, "index.ts");

const GENERATED_HEADER = "// Generated by generate.ts from resources/swagger.json. Do not edit by hand.";
const IDENTIFIER_PATTERN = /^[A-Za-z_$][A-Za-z0-9_$]*$/u;

const definitionNames = new Map<string, string>();

function capitalizeWord(word: string): string {
  if (word.length >= 2 && word === word.toUpperCase()) {
    return word.charAt(0) + word.slice(1).toLowerCase();
  }
  return word.charAt(0).toUpperCase() + word.slice(1);
}

function splitWords(value: string): string[] {
  return value.split(/[^A-Za-z0-9]+/u).filter((word) => word.length > 0);
}

function pascalCase(value: string): string {
  return splitWords(value).map(capitalizeWord).join("");
}

function camelCase(value: string): string {
  const pascal = pascalCase(value);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function kebabCase(value: string): string {
  return value.replace(/([a-z0-9])([A-Z])/gu, "$1-$2").toLowerCase();
}

function operationFunctionName(method: HttpMethod, operationPath: string): string {
  const words: string[] = [];
  for (const segment of operationPath.split("/")) {
    const expanded = segment.replace(/\{([^}]+)\}/gu, (_match, parameterName: string) => ` by ${parameterName} `);
    words.push(...splitWords(expanded));
  }
  return `${method}${words.length > 0 ? words.map(capitalizeWord).join("") : "Root"}`;
}

function quotePropertyName(name: string): string {
  return IDENTIFIER_PATTERN.test(name) ? name : JSON.stringify(name);
}

function parenthesize(type: string): string {
  return type.includes(" | ") || type.includes(" & ") ? `(${type})` : type;
}

function enumType(values: readonly (string | number | boolean)[]): string {
  return values.map((value) => JSON.stringify(value)).join(" | ");
}

function schemaToType(schema: SwaggerSchema | undefined, usedDefinitions: Set<string>): string {
  if (schema === undefined) {
    return "unknown";
  }
  if (schema.$ref !== undefined) {
    const sanitized = definitionNames.get(schema.$ref.replace("#/definitions/", ""));
    if (sanitized === undefined) {
      return "unknown";
    }
    usedDefinitions.add(sanitized);
    return sanitized;
  }
  if (schema.enum !== undefined) {
    return enumType(schema.enum);
  }
  if (schema.allOf !== undefined) {
    return schema.allOf.map((part) => parenthesize(schemaToType(part, usedDefinitions))).join(" & ");
  }
  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "file":
      return "ArrayBuffer";
    case "array":
      return `${parenthesize(schemaToType(schema.items, usedDefinitions))}[]`;
    default: {
      if (schema.properties !== undefined) {
        const requiredNames = new Set(schema.required ?? []);
        const entries = Object.entries(schema.properties).map(([propertyName, propertySchema]) => {
          const optionalMarker = requiredNames.has(propertyName) ? "" : "?";
          return `${quotePropertyName(propertyName)}${optionalMarker}: ${schemaToType(propertySchema, usedDefinitions)}`;
        });
        return entries.length === 0 ? "Record<string, unknown>" : `{ ${entries.join("; ")} }`;
      }
      if (typeof schema.additionalProperties === "object") {
        return `Record<string, ${schemaToType(schema.additionalProperties, usedDefinitions)}>`;
      }
      if (schema.type === "object" || schema.additionalProperties === true) {
        return "Record<string, unknown>";
      }
      return "unknown";
    }
  }
}

function renderDefinition(originalName: string, sanitizedName: string, schema: SwaggerSchema): string {
  const usedDefinitions = new Set<string>();
  // Springfox-specific fix (harmless elsewhere): it renders Iterable<X> as an
  // empty object, but those endpoints return JSON arrays of X.
  const iterableMatch = /^Iterable«(.+)»$/u.exec(originalName);
  if (iterableMatch !== null && schema.properties === undefined) {
    const primitiveInnerTypes: Readonly<Record<string, string>> = {
      string: "string",
      int: "number",
      long: "number",
      boolean: "boolean",
    };
    const innerName = definitionNames.get(iterableMatch[1]) ?? primitiveInnerTypes[iterableMatch[1]];
    return `export type ${sanitizedName} = ${innerName ?? "Record<string, unknown>"}[];`;
  }
  if (schema.properties !== undefined && schema.enum === undefined && schema.allOf === undefined) {
    const requiredNames = new Set(schema.required ?? []);
    const lines = Object.entries(schema.properties).map(([propertyName, propertySchema]) => {
      const optionalMarker = requiredNames.has(propertyName) ? "" : "?";
      return `  ${quotePropertyName(propertyName)}${optionalMarker}: ${schemaToType(propertySchema, usedDefinitions)};`;
    });
    return `export interface ${sanitizedName} {\n${lines.join("\n")}\n}`;
  }
  return `export type ${sanitizedName} = ${schemaToType(schema, usedDefinitions)};`;
}

interface ActionParameter {
  readonly propertyName: string;
  readonly wireName: string;
  readonly location: "path" | "query" | "header";
  readonly required: boolean;
  readonly type: string;
}

function queryParameterType(parameter: SwaggerParameter): string {
  if (parameter.enum !== undefined) {
    return enumType(parameter.enum);
  }
  switch (parameter.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    default: {
      if (parameter.type === "array" || parameter.items !== undefined) {
        const items = parameter.items;
        const itemType =
          items?.enum !== undefined
            ? enumType(items.enum)
            : items?.type === "integer" || items?.type === "number"
              ? "number"
              : items?.type === "boolean"
                ? "boolean"
                : "string";
        return `readonly ${parenthesize(itemType)}[]`;
      }
      return "string";
    }
  }
}

function headerParameterType(parameter: SwaggerParameter): string {
  if (parameter.enum !== undefined && parameter.enum.every((value) => typeof value === "string")) {
    return enumType(parameter.enum);
  }
  return "string";
}

function toActionParameters(operationPath: string, parameters: readonly SwaggerParameter[]): ActionParameter[] {
  const usedPropertyNames = new Set<string>();
  const claimPropertyName = (wireName: string): string => {
    let propertyName = camelCase(wireName);
    let suffix = 2;
    while (usedPropertyNames.has(propertyName)) {
      propertyName = `${camelCase(wireName)}${suffix}`;
      suffix += 1;
    }
    usedPropertyNames.add(propertyName);
    return propertyName;
  };

  const actionParameters = parameters
    .filter((parameter) => parameter.in === "path" || parameter.in === "query" || parameter.in === "header")
    .map<ActionParameter>((parameter) => {
      const propertyName = claimPropertyName(parameter.name);
      if (parameter.in === "path") {
        return {
          propertyName,
          wireName: parameter.name,
          location: "path",
          required: true,
          type: parameter.type === "integer" || parameter.type === "number" ? "number" : "string",
        };
      }
      if (parameter.in === "header") {
        return {
          propertyName,
          wireName: parameter.name,
          location: "header",
          required: parameter.required === true,
          type: headerParameterType(parameter),
        };
      }
      return {
        propertyName,
        wireName: parameter.name,
        location: "query",
        required: parameter.required === true,
        type: queryParameterType(parameter),
      };
    });

  // Some spec generators (e.g. springfox) declare a path-template variable as
  // a query parameter, or omit it entirely.
  for (const [, variableName] of operationPath.matchAll(/\{([^}]+)\}/gu)) {
    const declaredIndex = actionParameters.findIndex((parameter) => parameter.wireName === variableName);
    if (declaredIndex >= 0) {
      const declared = actionParameters[declaredIndex];
      if (declared.location === "query") {
        actionParameters[declaredIndex] = { ...declared, location: "path", required: true };
      }
      continue;
    }
    actionParameters.push({
      propertyName: claimPropertyName(variableName),
      wireName: variableName,
      location: "path",
      required: true,
      type: "string",
    });
  }

  return actionParameters;
}

function renderAction(
  functionName: string,
  method: HttpMethod,
  operationPath: string,
  operation: SwaggerOperation,
  parameters: readonly SwaggerParameter[],
): string {
  const pascalName = functionName.charAt(0).toUpperCase() + functionName.slice(1);
  const usedDefinitions = new Set<string>();
  const actionParameters = toActionParameters(operationPath, parameters);
  const pathParameters = actionParameters.filter((parameter) => parameter.location === "path");
  const queryParameters = actionParameters.filter((parameter) => parameter.location === "query");
  const headerParameters = actionParameters.filter((parameter) => parameter.location === "header");
  const bodyParameter = parameters.find((parameter) => parameter.in === "body");
  const bodyPropertyName = actionParameters.some((parameter) => parameter.propertyName === "body")
    ? "requestBody"
    : "body";
  const hasArgs = actionParameters.length > 0 || bodyParameter !== undefined;

  const pathTemplate = operationPath.replace(/\{([^}]+)\}/gu, (_match, wireName: string) => {
    const parameter = pathParameters.find((candidate) => candidate.wireName === wireName);
    if (parameter === undefined) {
      throw new Error(`Undeclared path parameter "${wireName}" in ${operationPath}`);
    }
    return `\${encodeURIComponent(String(args.${parameter.propertyName}))}`;
  });

  const successSchema = operation.responses?.["200"]?.schema ?? operation.responses?.["201"]?.schema;
  const outputType = successSchema === undefined ? undefined : schemaToType(successSchema, usedDefinitions);
  const bodyType = bodyParameter === undefined ? undefined : schemaToType(bodyParameter.schema, usedDefinitions);

  const sections: string[] = [GENERATED_HEADER];
  const clientImports = hasArgs ? "apiFetch, assertRequiredArguments" : "apiFetch";
  const importLines = [`import { ${clientImports}, type AuthInput } from "../client.js";`];
  if (usedDefinitions.size > 0) {
    const names = [...usedDefinitions].sort().join(", ");
    importLines.push(`import type { ${names} } from "../types.js";`);
  }
  sections.push(importLines.join("\n"));

  if (hasArgs) {
    const lines = actionParameters.map((parameter) => {
      const optionalMarker = parameter.required ? "" : "?";
      return `  ${quotePropertyName(parameter.propertyName)}${optionalMarker}: ${parameter.type};`;
    });
    if (bodyType !== undefined) {
      lines.push(`  ${bodyPropertyName}${bodyParameter?.required === true ? "" : "?"}: ${bodyType};`);
    }
    sections.push(`export interface ${pascalName}Args {\n${lines.join("\n")}\n}`);
  }

  if (outputType !== undefined) {
    sections.push(`export type ${pascalName}Output = ${outputType};`);
  }

  const methodLabel = method.toUpperCase();
  const docLines = [
    `${methodLabel} ${operationPath}${operation.summary !== undefined ? ` — ${operation.summary}` : ""}`,
  ];
  if (operation.deprecated === true) {
    docLines.push("@deprecated");
  }
  const doc =
    docLines.length === 1 ? `/** ${docLines[0]} */` : `/**\n${docLines.map((line) => ` * ${line}`).join("\n")}\n */`;

  const argsParameter = hasArgs ? `, args: ${pascalName}Args` : "";
  const returnType = outputType === undefined ? "void" : `${pascalName}Output`;
  const requestLines = [`    auth,`, `    method: ${JSON.stringify(methodLabel)},`, `    path: \`${pathTemplate}\`,`];
  if (queryParameters.length > 0) {
    const entries = queryParameters.map(
      (parameter) => `      ${JSON.stringify(parameter.wireName)}: args.${parameter.propertyName},`,
    );
    requestLines.push(`    query: {\n${entries.join("\n")}\n    },`);
  }
  if (headerParameters.length > 0) {
    const entries = headerParameters.map(
      (parameter) => `      ${JSON.stringify(parameter.wireName)}: args.${parameter.propertyName},`,
    );
    requestLines.push(`    headers: {\n${entries.join("\n")}\n    },`);
  }
  if (bodyParameter !== undefined) {
    requestLines.push(`    body: args.${bodyPropertyName},`);
  }
  requestLines.push(`    fields,`);
  const bodyLines: string[] = [];
  if (hasArgs) {
    const requiredNames = actionParameters
      .filter((parameter) => parameter.required)
      .map((parameter) => JSON.stringify(parameter.propertyName));
    if (bodyParameter?.required === true) {
      requiredNames.push(JSON.stringify(bodyPropertyName));
    }
    bodyLines.push(`  assertRequiredArguments(${JSON.stringify(functionName)}, args, [${requiredNames.join(", ")}]);`);
  }
  sections.push(
    [
      doc,
      `export async function ${functionName}(auth: AuthInput${argsParameter}, fields: readonly string[] | null = null): Promise<${returnType}> {`,
      ...bodyLines,
      `  return apiFetch<${returnType}>({`,
      ...requestLines,
      `  });`,
      `}`,
    ].join("\n"),
  );

  return `${sections.join("\n\n")}\n`;
}

async function main(): Promise<void> {
  const swagger = JSON.parse(await readFile(swaggerPath, "utf8")) as SwaggerDocument;
  const definitions = swagger.definitions ?? {};

  for (const originalName of Object.keys(definitions)) {
    const sanitized = pascalCase(originalName);
    if ([...definitionNames.values()].includes(sanitized)) {
      throw new Error(`Sanitized definition name collision: ${sanitized}`);
    }
    definitionNames.set(originalName, sanitized);
  }

  const definitionSections = [...definitionNames.entries()]
    .sort(([, a], [, b]) => a.localeCompare(b))
    .map(([originalName, sanitizedName]) => renderDefinition(originalName, sanitizedName, definitions[originalName]));
  await writeFile(typesPath, `${GENERATED_HEADER}\n\n${definitionSections.join("\n\n")}\n`);

  await rm(actionsDir, { recursive: true, force: true });
  await mkdir(actionsDir, { recursive: true });

  const enabledMethods = HTTP_METHODS.filter((method) => ENABLED_CATEGORIES[METHOD_CATEGORIES[method]]);
  const usedFunctionNames = new Set<string>();
  const usedFileNames = new Set<string>();
  const generatedCounts: Record<OperationCategory, number> = { read: 0, create: 0, update: 0, delete: 0 };
  let skippedCount = 0;

  for (const [operationPath, pathItem] of Object.entries(swagger.paths).sort(([a], [b]) => a.localeCompare(b))) {
    const pathLevelParameters = pathItem.parameters ?? [];
    for (const method of enabledMethods) {
      const operation = pathItem[method];
      if (operation === undefined) {
        continue;
      }
      const operationParameters = operation.parameters ?? [];
      const parameters = [
        ...operationParameters,
        ...pathLevelParameters.filter(
          (pathLevel) => !operationParameters.some((own) => own.name === pathLevel.name && own.in === pathLevel.in),
        ),
      ];
      const label = `${method.toUpperCase()} ${operationPath}`;
      const formDataParameters = parameters.filter((parameter) => parameter.in === "formData");
      if (formDataParameters.length > 0) {
        skippedCount += 1;
        console.warn(
          `SKIPPED ${label}: form-data parameters are not supported (${formDataParameters
            .map((parameter) => parameter.name)
            .join(", ")})`,
        );
        continue;
      }
      if (method === "get" && parameters.some((parameter) => parameter.in === "body")) {
        skippedCount += 1;
        console.warn(`SKIPPED ${label}: GET requests cannot carry a JSON body`);
        continue;
      }
      let functionName = operationFunctionName(method, operationPath);
      if (usedFunctionNames.has(functionName)) {
        let suffix = 2;
        while (usedFunctionNames.has(`${functionName}${suffix}`)) {
          suffix += 1;
        }
        console.warn(`RENAMED ${label}: ${functionName} collides, using ${functionName}${suffix}`);
        functionName = `${functionName}${suffix}`;
      }
      usedFunctionNames.add(functionName);
      let fileName = `${kebabCase(functionName)}.ts`;
      let fileSuffix = 2;
      while (usedFileNames.has(fileName)) {
        fileName = `${kebabCase(functionName)}-${fileSuffix}.ts`;
        fileSuffix += 1;
      }
      usedFileNames.add(fileName);
      await writeFile(
        path.join(actionsDir, fileName),
        renderAction(functionName, method, operationPath, operation, parameters),
      );
      generatedCounts[METHOD_CATEGORIES[method]] += 1;
    }
  }

  const exportLines = [...usedFileNames]
    .sort()
    .map((fileName) => `export * from "./actions/${fileName.replace(/\.ts$/u, "")}.js";`);
  await writeFile(indexPath, `${GENERATED_HEADER}\n\n${exportLines.join("\n")}\n`);

  const total = Object.values(generatedCounts).reduce((sum, count) => sum + count, 0);
  console.log(
    `Generated ${total} actions (read ${generatedCounts.read}, create ${generatedCounts.create}, update ${generatedCounts.update}, delete ${generatedCounts.delete}) and ${definitionNames.size} type definitions (${skippedCount} skipped).`,
  );
}

await main();
